foreground #f2f2f7
background #16181f
selection_foreground #eef3ff
selection_background #23324a

cursor #7aa2ff
cursor_text_color #0b1020

active_tab_foreground #0b1020
active_tab_background #7aa2ff
inactive_tab_foreground #b8bfcc
inactive_tab_background #1e212b

color0  #282c37
color1  #ff5f57
color2  #89dceb
color3  #9ec1ff
color4  #7aa2ff
color5  #89dceb
color6  #9ec1ff
color7  #f2f2f7

color8  #70788a
color9  #5b1f1b
color10 #183a42
color11 #23324a
color12 #263a63
color13 #89dceb
color14 #9ec1ff
color15 #f2f2f7

url_color #7aa2ff
