animations {
    enabled = true

    bezier = standard, 0.20, 0.90, 0.10, 1.00
    bezier = overshot, 0.13, 0.99, 0.29, 1.10
    bezier = smoothOut, 0.36, 0.00, 0.66, -0.56
    bezier = smoothIn, 0.25, 1.00, 0.50, 1.00

    animation = windows, 1, 6, standard, slide
    animation = windowsIn, 1, 6, overshot, slide
    animation = windowsOut, 1, 5, smoothOut, slide
    animation = border, 1, 8, standard
    animation = borderangle, 1, 8, standard
    animation = fade, 1, 6, standard
    animation = workspaces, 1, 6, standard, slidefade 15%
    animation = specialWorkspace, 1, 6, overshot, slidefadevert 15%
}
