exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE GTK_THEME
exec-once = hyprpaper
exec-once = ~/.local/bin/theme-apply
exec-once = mako
exec-once = waybar
exec-once = systemctl --user start hyprpolkitagent.service
