# ============================================================
# hyprland-shell
# production-oriented Hyprland environment
# ============================================================

# generated wallpaper + palette
source = ~/.config/theme/generated/hypr-colors.conf

# modular config
source = ~/.config/hypr/conf.d/00-monitors.conf
source = ~/.config/hypr/conf.d/10-environment.conf
source = ~/.config/hypr/conf.d/20-input.conf
source = ~/.config/hypr/conf.d/30-general.conf
source = ~/.config/hypr/conf.d/40-decoration.conf
source = ~/.config/hypr/conf.d/50-animations.conf
source = ~/.config/hypr/conf.d/60-layout.conf
source = ~/.config/hypr/conf.d/70-rules.conf
source = ~/.config/hypr/conf.d/80-binds.conf
source = ~/.config/hypr/conf.d/90-autostart.conf
