[config]
mode = "dark"
caching = true

[templates.colors_css]
input_path = '~/.config/theme/matugen/templates/colors.css'
output_path = '~/.config/theme/generated/colors.css'

[templates.hypr]
input_path = '~/.config/theme/matugen/templates/hypr-colors.conf'
output_path = '~/.config/theme/generated/hypr-colors.conf'

[templates.rofi]
input_path = '~/.config/theme/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/theme/generated/rofi-colors.rasi'

[templates.kitty]
input_path = '~/.config/theme/matugen/templates/kitty-theme.conf'
output_path = '~/.config/theme/generated/kitty-theme.conf'

[templates.mako]
input_path = '~/.config/theme/matugen/templates/mako.conf'
output_path = '~/.config/mako/config'

[templates.dock]
input_path = '~/.config/theme/matugen/templates/nwg-dock.css'
output_path = '~/.config/theme/generated/nwg-dock.css'

[templates.palette_json]
input_path = '~/.config/theme/matugen/templates/colors.json'
output_path = '~/.config/theme/generated/colors.json'

[templates.gtkgreet]
input_path = '~/.config/theme/matugen/templates/gtkgreet.css'
output_path = '~/.config/theme/generated/gtkgreet.css'
