color_theme = "/home/$USER/.config/btop/themes/matugen.theme"
theme_background = False
truecolor = True
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_tree = True
proc_gradient = True
check_temp = True
vim_keys = True
cpu_sensor = "Auto"
show_gpu_info = Auto
